### PR TITLE
Branch demo1

### PR DESCRIPTION
**Pull request by logigeardn2018**

### CODE REVIEW

**Comment by vantruongt2** [comment]
asdasdasdasd

**Comment by vantruongt2** [comment]
asdasdasd

**Comment by vantruongt2** [comment]
asdasdasdasdasd

**Comment by vantruongt2** [comment]
asdasdasd

**Comment by vantruongt2** [comment]
ok to test

**Comment by vantruongt2** [comment]
ok

**Comment by vantruongt2** [comment]
asdasd

**Comment by vantruongt2** [comment]
ok to test

**Comment by vantruongt2** [comment]
asdasdasd

**Comment by logigeardn2018** [comment]
retest this please

**Pull request closed without merging**
